language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t amadinathaniel/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true amadinathaniel/docker-react npm run test